.TH BADARITH 1 "1 August 2023" "badarith-1.2" "badarith's manual"
.SH NAME
\fBbadarith \fP- performs badly implemented arithmetic operations
\fB
.SH SYNOPSIS
.nf
.fam C
\fBbadarith\fP

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
\fBbadarith\fP performs badly implemented arithmetic operations. It depends on libbadmath to perform its calculations.
.SH AUTHOR
\fBbadarith\fP was written by David da Silva Polverari <david.polverari@gmail.com>.
